### ISSUE TITLE
bro stop spamming state updates

### ISSUE THREAD

**Issue by Seqi** [jmsv/thing-is-turing-complete#1]
bro ur updating state like 3 times and they racin and rerendering your shit and your shit be recreating that function

pls use an immutable object as a single state to capture all 3 fields and use `useCallback` for ur callback

also u got an empty `h3` if not loading

if youre testing new react shit you should look into `React.Suspense` for concurrent rendering so you dont have to manage error and loading state at the core component level

**Comment by jmsv** [comment]
bro thanks for taking the time to check out my stuff bro but really i made this hella quick to annoy @bahorn for a while as a break from coursework

suspense looks super cool and imma check it out soonish when i gots more time ayo

feel free to open a pr with ur suggestions tho but beware this was very much a throwaway kinda jobbie

**Comment by bahorn** [comment]
Yeah, this was basically something he made to annoy me as i was trying to leak the source of the isTuringComplete function when he was running it on input I gave him on Messenger.

**Comment by Seqi** [comment]
i just wanted to flex some new shit i learned a week ago and act like im a source of credibility on react now carry on fellas
